# Generated by Django 3.1.1 on 2021-05-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clone',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('qs_id', models.CharField(max_length=20, unique=True, verbose_name='QS ID')),
                ('alt_id', models.CharField(max_length=20, verbose_name='Alternate ID')),
                ('species', models.CharField(max_length=50, verbose_name='Species')),
                ('origin', models.TextField(blank=True, verbose_name='Origin Location')),
                ('origin_coords', models.CharField(blank=True, max_length=50, verbose_name='Origin Coordinates')),
                ('box_plated_from', models.CharField(blank=True, max_length=100, verbose_name='Box plated from')),
                ('collect_date', models.DateField(blank=True, null=True, verbose_name='Date Collected')),
                ('freeze_date', models.DateField(blank=True, null=True, verbose_name='Date Frozen')),
                ('collect_method', models.CharField(blank=True, max_length=20, verbose_name='Collection Method')),
                ('culture_method', models.CharField(blank=True, max_length=20, verbose_name='Culture Method')),
                ('origin_soil_sample', models.CharField(blank=True, max_length=20, verbose_name='Origin Soil Sample')),
                ('freezer_loc', models.CharField(blank=True, max_length=20, verbose_name='Location in Freezer')),
                ('box_name', models.CharField(blank=True, max_length=100, verbose_name='Box Name')),
                ('box_initials', models.CharField(blank=True, max_length=20, verbose_name='Box Initials')),
                ('is_clonal', models.BooleanField(blank=True, null=True, verbose_name='Is Clonal')),
                ('mating_type', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mating Type')),
                ('viol_hap_grp', models.CharField(blank=True, max_length=10, verbose_name='vio.hap.grp')),
                ('sequenced', models.CharField(blank=True, max_length=20, verbose_name='Sequenced')),
                ('is_amo', models.BooleanField(blank=True, null=True, verbose_name='Amoebophilis Endosymbiont')),
                ('is_chlam', models.BooleanField(blank=True, null=True, verbose_name='Neochlamydia Endosymbiont')),
                ('chlam_hap', models.CharField(blank=True, max_length=10, verbose_name='Neochlamydia Haplotype')),
                ('endo_hap_id', models.CharField(blank=True, max_length=50, verbose_name='Endosymbiont Haplotype ID')),
                ('endo_seq_hit', models.CharField(blank=True, max_length=100, verbose_name='Endosymbiont 16S Sequence Hit')),
                ('burk_species', models.CharField(blank=True, max_length=50, verbose_name='Paraburkholderia Species')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(max_length=100, unique=True, verbose_name='DOI')),
                ('title', models.TextField()),
                ('first_author', models.CharField(max_length=50, verbose_name='First Author')),
                ('last_author', models.CharField(max_length=50, verbose_name='Last Author')),
                ('journal', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('clones', models.ManyToManyField(to='db_app.Clone', verbose_name='Clones used')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
