# Generated by Django 3.1.1 on 2020-10-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clone',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('qsID', models.CharField(max_length=20, unique=True, verbose_name='QS ID')),
                ('altID', models.CharField(max_length=20, unique=True, verbose_name='Alternate ID')),
                ('origin', models.TextField(blank=True, verbose_name='Origin Location')),
                ('originCoords', models.CharField(blank=True, max_length=50, verbose_name='Origin Coordinates')),
                ('boxPlatedFrom', models.CharField(blank=True, max_length=100, verbose_name='Box plated from')),
                ('collectDate', models.DateField(blank=True, null=True, verbose_name='Date Collected')),
                ('freezeDate', models.DateField(blank=True, null=True, verbose_name='Date Frozen')),
                ('collectMethod', models.CharField(blank=True, max_length=20, verbose_name='Collection Method')),
                ('cultureMethod', models.CharField(blank=True, max_length=20, verbose_name='Culture Method')),
                ('originSoilSample', models.CharField(blank=True, max_length=20, verbose_name='Origin Soil Sample')),
                ('isFarmer', models.BooleanField(blank=True, verbose_name='Is a Farmer')),
                ('species', models.CharField(max_length=50)),
                ('freezerLoc', models.CharField(blank=True, max_length=20, verbose_name='Location in Freezer')),
                ('boxName', models.CharField(blank=True, max_length=100, verbose_name='Box Name')),
                ('boxInitials', models.CharField(blank=True, max_length=20, verbose_name='Box Initials')),
                ('isClonal', models.BooleanField(blank=True, verbose_name='Is Clonal')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(max_length=100, unique=True, verbose_name='DOI')),
                ('title', models.TextField()),
                ('firstAuthor', models.CharField(max_length=50, verbose_name='First Author')),
                ('lastAuthor', models.CharField(max_length=50, verbose_name='Last Author')),
                ('journal', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('clones', models.ManyToManyField(to='db_app.Clone', verbose_name='Clones used')),
            ],
        ),
    ]
