# Generated by Django 3.1.1 on 2020-12-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clone',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-year']},
        ),
    ]
