# Generated by Django 3.1.1 on 2021-05-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clone',
            name='viol_hap_grp',
            field=models.CharField(blank=True, max_length=10, verbose_name='viol.hap.grp'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=100, verbose_name='DOI'),
        ),
    ]
