# Generated by Django 3.1.1 on 2021-02-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_auto_20210218_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clone',
            name='isClonal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Clonal'),
        ),
    ]
