# Generated by Django 3.1.1 on 2021-04-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_auto_20210224_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clone',
            name='collectDate',
            field=models.DateField(blank=True, default='&nbsp', null=True, verbose_name='Date Collected'),
        ),
        migrations.AlterField(
            model_name='clone',
            name='freezeDate',
            field=models.DateField(blank=True, default='&nbsp', null=True, verbose_name='Date Frozen'),
        ),
        migrations.AlterField(
            model_name='clone',
            name='isAmo',
            field=models.BooleanField(blank=True, default='&nbsp', null=True, verbose_name='Amoebophilis Endosymbiont'),
        ),
        migrations.AlterField(
            model_name='clone',
            name='isChlam',
            field=models.BooleanField(blank=True, default='&nbsp', null=True, verbose_name='Neochlamydia Endosymbiont'),
        ),
        migrations.AlterField(
            model_name='clone',
            name='isClonal',
            field=models.BooleanField(blank=True, default='&nbsp', null=True, verbose_name='Is Clonal'),
        ),
    ]
