# Generated by Django 3.1.1 on 2021-05-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0009_clone_mating_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clone',
            name='burk_species',
            field=models.CharField(blank=True, max_length=50, verbose_name='Paraburkholderia Species'),
        ),
    ]
